
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Cfg.Game
{
public abstract partial class NoteUnit : Luban.BeanBase
{
    public NoteUnit(ByteBuf _buf) 
    {
        TimeMs = _buf.ReadInt();
        Effect = _buf.ReadString();
        Sound = _buf.ReadString();
        Score = _buf.ReadInt();
    }

    public static NoteUnit DeserializeNoteUnit(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case Game.SideNoteUnit.__ID__: return new Game.SideNoteUnit(_buf);
            case Game.TrackNoteUnit.__ID__: return new Game.TrackNoteUnit(_buf);
            default: throw new SerializationException();
        }
    }

    /// <summary>
    /// 时间，毫秒
    /// </summary>
    public readonly int TimeMs;
    /// <summary>
    /// 特效
    /// </summary>
    public readonly string Effect;
    /// <summary>
    /// 音效
    /// </summary>
    public readonly string Sound;
    /// <summary>
    /// 分数
    /// </summary>
    public readonly int Score;
   

    public virtual void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "timeMs:" + TimeMs + ","
        + "effect:" + Effect + ","
        + "sound:" + Sound + ","
        + "score:" + Score + ","
        + "}";
    }
}

}
