
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Cfg.Game
{
public sealed partial class TrackNoteUnit : Game.NoteUnit
{
    public TrackNoteUnit(ByteBuf _buf)  : base(_buf) 
    {
        StartPosition = ExternalTypeUtil.NewVector2(vector2.Deserializevector2(_buf));
        EndPosition = ExternalTypeUtil.NewVector2(vector2.Deserializevector2(_buf));
        Count = _buf.ReadInt();
        DurationMs = _buf.ReadInt();
    }

    public static TrackNoteUnit DeserializeTrackNoteUnit(ByteBuf _buf)
    {
        return new Game.TrackNoteUnit(_buf);
    }

    /// <summary>
    /// 起始位置，像素坐标
    /// </summary>
    public readonly UnityEngine.Vector2 StartPosition;
    /// <summary>
    /// 结束位置，像素坐标
    /// </summary>
    public readonly UnityEngine.Vector2 EndPosition;
    /// <summary>
    /// 音符数量
    /// </summary>
    public readonly int Count;
    /// <summary>
    /// 持续时间
    /// </summary>
    public readonly int DurationMs;
   
    public const int __ID__ = 389362181;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "timeMs:" + TimeMs + ","
        + "effect:" + Effect + ","
        + "sound:" + Sound + ","
        + "score:" + Score + ","
        + "startPosition:" + StartPosition + ","
        + "endPosition:" + EndPosition + ","
        + "count:" + Count + ","
        + "durationMs:" + DurationMs + ","
        + "}";
    }
}

}
