
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Cfg.Game
{
public sealed partial class SideNoteUnit : Game.NoteUnit
{
    public SideNoteUnit(ByteBuf _buf)  : base(_buf) 
    {
        Position = ExternalTypeUtil.NewVector2(vector2.Deserializevector2(_buf));
        Direction = (Game.SideNoteDirection)_buf.ReadInt();
        Speed = _buf.ReadInt();
        DurationMs = _buf.ReadInt();
    }

    public static SideNoteUnit DeserializeSideNoteUnit(ByteBuf _buf)
    {
        return new Game.SideNoteUnit(_buf);
    }

    /// <summary>
    /// 位置，像素坐标
    /// </summary>
    public readonly UnityEngine.Vector2 Position;
    /// <summary>
    /// 方向
    /// </summary>
    public readonly Game.SideNoteDirection Direction;
    /// <summary>
    /// 速度
    /// </summary>
    public readonly int Speed;
    /// <summary>
    /// 持续时间
    /// </summary>
    public readonly int DurationMs;
   
    public const int __ID__ = -267871351;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "timeMs:" + TimeMs + ","
        + "effect:" + Effect + ","
        + "sound:" + Sound + ","
        + "score:" + Score + ","
        + "position:" + Position + ","
        + "direction:" + Direction + ","
        + "speed:" + Speed + ","
        + "durationMs:" + DurationMs + ","
        + "}";
    }
}

}
