
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Cfg.Game
{ 
    public enum SideNoteDirection
    {
        /// <summary>
        /// 左
        /// </summary>
        Left = 0,
        /// <summary>
        /// 右
        /// </summary>
        Right = 1,
    }

} 

