
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Cfg
{
public sealed partial class LevelConfig : Luban.BeanBase
{
    public LevelConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        VideoPath = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Notes = new System.Collections.Generic.List<Game.NoteUnit>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Game.NoteUnit _e0;  _e0 = Game.NoteUnit.DeserializeNoteUnit(_buf); Notes.Add(_e0);}}
    }

    public static LevelConfig DeserializeLevelConfig(ByteBuf _buf)
    {
        return new LevelConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 视频路径
    /// </summary>
    public readonly string VideoPath;
    public readonly System.Collections.Generic.List<Game.NoteUnit> Notes;
   
    public const int __ID__ = -1308229690;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        foreach (var _e in Notes) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "videoPath:" + VideoPath + ","
        + "notes:" + Luban.StringUtil.CollectionToString(Notes) + ","
        + "}";
    }
}

}
