
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Cysharp.Threading.Tasks;

namespace Game.Cfg
{
public partial class Tables
{
    public Game.TbLevelConfig TbLevelConfig {get; private set; }

    public async UniTask LoadAll(System.Func<string, UniTask<ByteBuf>> loader)
    {
        var tasks = new UniTask[]
        {      
            UniTask.Create(async () => TbLevelConfig = new Game.TbLevelConfig(await loader("game_tblevelconfig"))),
        };
        await UniTask.WhenAll(tasks);
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbLevelConfig.ResolveRef(this);
    }
}

}
